### ISSUE TITLE
weird training results

### ISSUE THREAD

**Issue by LonglongaaaGo** [blackprotoss/GSDM#7]
Hi @blackprotoss 

Thanks for your awesome work.
I tried to train the structural prediction model for 50 epochs on the ST dataset.
But the testing results are not perfect, could you give some advice for improving?
<img width="361" alt="image" src="https://github.com/blackprotoss/GSDM/assets/34880268/5c7a0972-fb1c-4abd-855e-8804e7c7fa81">

**Comment by blackprotoss** [comment]
we have re-checked our released code and confirmed the reproducibility. Since we have not encountered such a problem before, one possible guess is that it might be related to the image channels or RGB issues.

**Comment by LonglongaaaGo** [comment]
Hi @blackprotoss ,
Thanks for the reply.
One thing I am not sure of is that the original CNN model only returns the final CNN features.
I also changed the code to run it successfully by adding final feature maps from the last layer conv.
As shown below, I am still determining if i am correct, could you help with this?
I appreciate!

![image](https://github.com/blackprotoss/GSDM/assets/34880268/a0a5d71e-89a9-40af-be24-dd87c425aa06)

**Comment by blackprotoss** [comment]
My mistake, I forgot to upload one folder crnn (some critical code files here). The files have been updated.

**Comment by LonglongaaaGo** [comment]
Hi @blackprotoss ,
Got!
thank you so much for the help!
